In [ ]:
# import numpy as np
# import pandas as pd

In [ ]:
# data = {
#     'name':['jhon','anna','peter','linda'],
#     'age':[20,39,49,59],
#     'city': ['new youk','paris','barlin','londaon'],
#     'salary':[5500,2000,29999,3000]
# }

# df = pd.DataFrame(data)
# df

    name  age      city  salary
0   jhon   20  new youk    5500
1   anna   39     paris    2000
2  peter   49    barlin   29999
3  linda   59   londaon    3000

In [ ]:
# data_list = [
#     ['jhon',20,'new yourk',70000],
#     ['anna',34,'inida',9999999],
#     ['anshu',19,'bihar',9888480]
# ]
# df2 = pd.DataFrame(data_list)
# columns = ["name","age","city","salary"]
# df2 = pd.DataFrame(data_list, columns=columns)
# df2

    name  age       city   salary
0   jhon   20  new yourk    70000
1   anna   34      inida  9999999
2  anshu   19      bihar  9888480

In [ ]:
# df2[['name','city']]

    name       city
0   jhon  new yourk
1   anna      inida
2  anshu      bihar

# creating a new column

In [14]:
# df2["desigination"] = ["doctor","eng","docotor","eng"]
# df2

In [15]:
#selection a  row
df2.loc[[0,1]]

   name  age       city   salary
0  jhon   20  new yourk    70000
1  anna   34      inida  9999999

In [22]:
#slection subset of rown and columns

df2.loc[[0,1]][["city","salary"]]
df2.loc[[1,2]][["name","age"]]

    name  age
1   anna   34
2  anshu   19

# conditional selections

In [31]:
# print(df2)

# print age greater than 20 
df2[df2["age"]> 19]

# i only want who age is 30 and there city must be paris

df2[df2["age"]>30  & (df2["city"] == "india")]

    name  age       city   salary
0   jhon   20  new yourk    70000
1   anna   34      inida  9999999
2  anshu   19      bihar  9888480