In [ ]:
import pandas as pd
import numpy as np

# merging two data frame

In [2]:
employees = pd.DataFrame({
    'employee_id': [1,2,3,4,5],
    'name': ['john','anna','peter','linda','bob'],
    'department': ['hr','it','finannce','it','hr']
})

# dataframe 2: salary information
salaries = pd.DataFrame({
    'employee_id': [1,2,3,6,7],
    'slary': [6000,80000,650000,70000,90000],
    'bonus': [5000,10000,70000,8000,12000]
})

In [3]:
employees

   employee_id   name department
0            1   john         hr
1            2   anna         it
2            3  peter   finannce
3            4  linda         it
4            5    bob         hr

In [4]:
salaries

   employee_id   slary  bonus
0            1    6000   5000
1            2   80000  10000
2            3  650000  70000
3            6   70000   8000
4            7   90000  12000

In [6]:
pd.merge(employees,salaries,on='employee_id')

   employee_id   name department   slary  bonus
0            1   john         hr    6000   5000
1            2   anna         it   80000  10000
2            3  peter   finannce  650000  70000

In [7]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department   slary  bonus
0            1   john         hr    6000   5000
1            2   anna         it   80000  10000
2            3  peter   finannce  650000  70000

In [8]:
pd.merge(employees,salaries,on='employee_id',how='left')

   employee_id   name department     slary    bonus
0            1   john         hr    6000.0   5000.0
1            2   anna         it   80000.0  10000.0
2            3  peter   finannce  650000.0  70000.0
3            4  linda         it       NaN      NaN
4            5    bob         hr       NaN      NaN

# contantication in data frames

In [9]:
df1 = pd.DataFrame({
    'A': ['A0','A1','A2'],
    'B': ['B0','B1','B2'],
    'C':['C0','C1','C2']
})

df2 = pd.DataFrame({
    'A': ['A3','A4','A5'],
    'B': ['B3','B4','B5'],
    'C': ['C3','C4','C5']
})

In [10]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [11]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [12]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [13]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5

# joining 2 data frame

In [14]:
df1 = pd.DataFrame({
    'name': ['Alice','bob','charlie']
},index = [1,2,3])

#second dataframe
df2 = pd.DataFrame({
    'score':[85,90,75]
},index = [2,3,4])

In [15]:
df1

      name
1    Alice
2      bob
3  charlie

In [16]:
df2

   score
2     85
3     90
4     75

In [ ]:
df1.join(df2,how = 'inner')

      name  score
1    Alice    NaN
2      bob   85.0
3  charlie   90.0
4      NaN   75.0

In [ ]:
df2.join(df1)

   score     name
2     85      bob
3     90  charlie
4     75      NaN