In [1]:
import pandas as pd
import numpy as np

# finding missing data

In [18]:
data = {
    'A': [1,2,np.nan,4,5],
    'B': [1,2,3,4,5],
    'C': [1,2,3,np.nan,np.nan],
    'D': [1,np.nan,np.nan,np.nan,5]
}

df = pd.DataFrame(data)
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [19]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [20]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [21]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

# remove missing data

In [22]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [23]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
# no rows null value they use it
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

# filling missing data

In [26]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [30]:
# har column ke liye diffrent column

values = {'A':0,'B':100,"C":400,"D":500}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  500.0
2  0.0  3    3.0  500.0
3  4.0  4  400.0  500.0
4  5.0  5  400.0    5.0

In [31]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [32]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0